# Generated by Django 3.0.5 on 2020-11-10 06:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import kisahkita_art.models


class Migration(migrations.Migration):

    dependencies = [
        ('kisahkita_art', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('image', models.ImageField(upload_to=kisahkita_art.models.categories_to)),
                ('slug', models.SlugField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kisahkita_art.Posting')),
            ],
        ),
        migrations.AddField(
            model_name='posting',
            name='categories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kisahkita_art.Categories'),
            preserve_default=False,
        ),
    ]
