# Generated by Django 3.0.5 on 2020-11-17 23:58

from django.db import migrations, models
import kisahkita_art.models


class Migration(migrations.Migration):

    dependencies = [
        ('kisahkita_art', '0004_comment_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='images',
            field=models.ImageField(max_length=500, upload_to=kisahkita_art.models.posting_to),
        ),
    ]
