# Generated by Django 3.0.5 on 2020-11-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kisahkita_art', '0005_auto_20201118_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='viewed',
            field=models.IntegerField(default=0),
        ),
    ]
