# Generated by Django 3.0.5 on 2020-12-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kisahkita_art', '0007_auto_20201130_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
