# Generated by Django 3.0.5 on 2020-12-04 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kisahkita_art', '0008_auto_20201201_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='kisahkita_art.Posting'),
        ),
    ]
