# Generated by Django 3.0.5 on 2020-12-07 10:12

from django.db import migrations, models
import kisahkita_art.models


class Migration(migrations.Migration):

    dependencies = [
        ('kisahkita_art', '0010_comment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(default='image/user.png', upload_to=kisahkita_art.models.comment_to),
        ),
    ]
