# Generated by Django 3.0.5 on 2020-12-07 10:15

from django.db import migrations, models
import kisahkita_art.models


class Migration(migrations.Migration):

    dependencies = [
        ('kisahkita_art', '0011_auto_20201207_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(default='', upload_to=kisahkita_art.models.comment_to),
        ),
    ]
