# Generated by Django 3.0.5 on 2020-12-07 15:52

from django.db import migrations, models
import django.db.models.deletion
import kisahkita_art.models


class Migration(migrations.Migration):

    dependencies = [
        ('kisahkita_art', '0012_auto_20201207_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(default='image/user.png', upload_to=kisahkita_art.models.comment_to),
        ),
        migrations.AlterField(
            model_name='posting',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting_categories', to='kisahkita_art.Categories'),
        ),
    ]
