# Generated by Django 3.0.5 on 2020-12-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kisahkita_art', '0013_auto_20201207_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
