# Generated by Django 3.0.5 on 2020-11-26 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='image_project_1',
            new_name='image_1',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='image_project_2',
            new_name='image_2',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='kejelasan',
            new_name='kelebihan',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='kejelasan1',
            new_name='pengertian',
        ),
    ]
